export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS"
export const FETCH_CHARACTERS = "FETCH_CHARACTERS"
export const MALE_CHECKBOX= "MALE_CHECKBOX";
export const FEMALE_CHECKBOX="FEMALE_CHECKBOX";
export const ALIVE_CHECKBOX = "ALIVE_CHECKBOX";
export const DEAD_CHECKBOX = "DEAD_CHECKBOX";
export const UNKNOWN_CHECKBOX = "UNKNOWN_CHECKBOX";

